# Generated by Django 3.2.16 on 2023-02-15 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_shipaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipaddress',
            name='phone_number',
            field=models.IntegerField(blank=True, default='', validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
