# Generated by Django 3.2.16 on 2023-02-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_auto_20230221_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardpayment',
            name='order',
        ),
    ]
