# Generated by Django 3.2.16 on 2023-01-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPart', '0003_remove_customuser_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='last name'),
        ),
    ]
