# Generated by Django 3.2.16 on 2023-01-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPart', '0005_remove_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=None, max_length=60, null=True, verbose_name='username'),
        ),
    ]
