# Generated by Django 3.2.16 on 2023-01-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPart', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
    ]
