# Generated by Django 3.2.16 on 2023-01-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPart', '0007_auto_20230113_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=None, max_length=60, null=True, unique=True, verbose_name='username'),
        ),
    ]
